<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class AgentsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('agents')->insert([
            [
                'id' => 1,
                'ability_id' => 1,
                'name' => 'Gekko',
                'description' => 'Gekko the Angeleno leads a tight-knit crew of calamitous creatures. His buddies bound forward, scattering enemies out of the way, with Gekko chasing them down to regroup and go again.',
                'role' => 'Initiator',
                'role_description' => 'Initiators challenge angles by setting up their team to enter contested ground and push defenders away.',
                'icon' => 'https://media.valorant-api.com/agents/e370fa57-4757-3604-3648-499e1f642d3f/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/1b47567f-8f7b-444b-aae3-b0c634622d10/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/e370fa57-4757-3604-3648-499e1f642d3f/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/e370fa57-4757-3604-3648-499e1f642d3f/background.png',
                'color' => '#c7f458ff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 2,
                'ability_id' => 2,
                'name' => 'Fade',
                'description' => 'Turkish bounty hunter Fade unleashes the power of raw nightmare to seize enemy secrets. Attuned with terror itself, she hunts down targets and reveals their deepest fears - before crushing them in the dark.',
                'role' => 'Initiator',
                'role_description' => 'Initiators challenge angles by setting up their team to enter contested ground and push defenders away.',
                'icon' => 'https://media.valorant-api.com/agents/dade69b4-4f5a-8528-247b-219e5a1facd6/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/1b47567f-8f7b-444b-aae3-b0c634622d10/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/dade69b4-4f5a-8528-247b-219e5a1facd6/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/dade69b4-4f5a-8528-247b-219e5a1facd6/killfeedportrait.png',
                'color' => '#b1414cff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 3,
                'ability_id' => 3,
                'name' => 'Breach',
                'description' => 'The bionic Swede Breach fires powerful, targeted kinetic blasts to aggressively clear a path through enemy ground. The damage and disruption he inflicts ensures no fight is ever fair.',
                'role' => 'Initiator',
                'role_description' => 'Initiators challenge angles by setting up their team to enter contested ground and push defenders away.',
                'icon' => 'https://media.valorant-api.com/agents/5f8d3a7f-467b-97f3-062c-13acf203c006/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/1b47567f-8f7b-444b-aae3-b0c634622d10/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/5f8d3a7f-467b-97f3-062c-13acf203c006/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/5f8d3a7f-467b-97f3-062c-13acf203c006/background.png',
                'color' => '#ff9c33ff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 4,
                'ability_id' => 4,
                'name' => 'Deadlock',
                'description' => 'Norwegian operative Deadlock deploys an array of cutting-edge nanowire to secure the battlefield from even the most lethal assault. No one escapes her vigilant watch, nor survives her unyielding ferocity.',
                'role' => 'Sentinel',
                'role_description' => 'Sentinels are defensive experts who can lock down areas and watch flanks, both on attacker and defender rounds.',
                'icon' => 'https://media.valorant-api.com/agents/cc8b64c8-4b25-4ff9-6e7f-37b4da43d235/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/5fc02f99-4091-4486-a531-98459a3e95e9/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/cc8b64c8-4b25-4ff9-6e7f-37b4da43d235/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/cc8b64c8-4b25-4ff9-6e7f-37b4da43d235/background.png',
                'color' => '#bcc2ffff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 5,
                'ability_id' => 5,
                'name' => 'Raze',
                'description' => 'Raze explodes out of Brazil with her big personality and big guns. With her blunt-force-trauma playstyle, she excels at flushing entrenched enemies and clearing tight spaces with a generous dose of boom.',
                'role' => 'Duelist',
                'role_description' => 'Duelists are self-sufficient fraggers who their team expects, through abilities and skills, to get high frags and seek out engagements first.',
                'icon' => 'https://media.valorant-api.com/agents/f94c3b30-42be-e959-889c-5aa313dba261/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/dbe8757e-9e92-4ed4-b39f-9dfc589691d4/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/f94c3b30-42be-e959-889c-5aa313dba261/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/f94c3b30-42be-e959-889c-5aa313dba261/background.png',
                'color' => '#feac45ff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 6,
                'ability_id' => 6,
                'name' => 'Chamber',
                'description' => 'Well-dressed and well-armed, French weapons designer Chamber expels aggressors with deadly precision. He leverages his custom arsenal to hold the line and pick off enemies from afar, with a contingency built for every plan.',
                'role' => 'Sentinel',
                'role_description' => 'Sentinels are defensive experts who can lock down areas and watch flanks, both on attacker and defender rounds.',
                'icon' => 'https://media.valorant-api.com/agents/22697a3d-45bf-8dd7-4fec-84a9e28c69d7/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/5fc02f99-4091-4486-a531-98459a3e95e9/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/22697a3d-45bf-8dd7-4fec-84a9e28c69d7/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/22697a3d-45bf-8dd7-4fec-84a9e28c69d7/killfeedportrait.png',
                'color' => '#ffce6fff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 7,
                'ability_id' => 7,
                'name' => 'KAY/O',
                'description' => 'KAY/O is a machine of war built for a single purpose: neutralizing radiants. His power to Suppress enemy abilities dismantles his opponents\' capacity to fight back, securing him and his allies the ultimate edge.',
                'role' => 'Initiator',
                'role_description' => 'Initiators challenge angles by setting up their team to enter contested ground and push defenders away.',
                'icon' => 'https://media.valorant-api.com/agents/601dbbe7-43ce-be57-2a40-4abd24953621/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/1b47567f-8f7b-444b-aae3-b0c634622d10/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/601dbbe7-43ce-be57-2a40-4abd24953621/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/601dbbe7-43ce-be57-2a40-4abd24953621/background.png',
                'color' => '#4afaffff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 8,
                'ability_id' => 8,
                'name' => 'Skye',
                'description' => 'Hailing from Australia, Skye and her band of beasts trailblaze the way through hostile territory. With her creations hampering the enemy, and her power to heal others, the team is strongest and safest by Skye\'s side.',
                'role' => 'Initiator',
                'role_description' => 'Initiators challenge angles by setting up their team to enter contested ground and push defenders away.',
                'icon' => 'https://media.valorant-api.com/agents/6f2a04ca-43e0-be17-7f36-b3908627744d/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/1b47567f-8f7b-444b-aae3-b0c634622d10/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/6f2a04ca-43e0-be17-7f36-b3908627744d/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/6f2a04ca-43e0-be17-7f36-b3908627744d/background.png',
                'color' => '#94e789ff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 9,
                'ability_id' => 9,
                'name' => 'Cypher',
                'description' => 'The Moroccan information broker, Cypher is a one-man surveillance network who keeps tabs on the enemy\'s every move. No secret is safe. No maneuver goes unseen. Cypher is always watching.',
                'role' => 'Sentinel',
                'role_description' => 'Sentinels are defensive experts who can lock down areas and watch flanks, both on attacker and defender rounds.',
                'icon' => 'https://media.valorant-api.com/agents/117ed9e3-49f3-6512-3ccf-0cada7e3823b/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/5fc02f99-4091-4486-a531-98459a3e95e9/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/117ed9e3-49f3-6512-3ccf-0cada7e3823b/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/117ed9e3-49f3-6512-3ccf-0cada7e3823b/background.png',
                'color' => '#db9b75ff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 10,
                'ability_id' => 10,
                'name' => 'Sova',
                'description' => 'Born from the eternal winter of Russia\'s tundra, Sova tracks, finds, and eliminates enemies with ruthless efficiency and precision. His custom bow and incredible scouting abilities ensure that even if you run, you cannot hide',
                'role' => 'Initiator',
                'role_description' => 'Initiators challenge angles by setting up their team to enter contested ground and push defenders away.',
                'icon' => 'https://media.valorant-api.com/agents/ded3520f-4264-bfed-162d-b080e2abccf9/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/1b47567f-8f7b-444b-aae3-b0c634622d10/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/320b2a48-4d9b-a075-30f1-1f93a9b638fa/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/320b2a48-4d9b-a075-30f1-1f93a9b638fa/background.png',
                'color' => '#f7c7a5ff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 11,
                'ability_id' => 11,
                'name' => 'Killjoy',
                'description' => 'The genius of Germany, Killjoy effortlessly secures key battlefield positions with her arsenal of inventions. If their damage doesn\'t take her enemies out, the debuff her robots provide will make short work of them.',
                'role' => 'Sentinel',
                'role_description' => 'Sentinels are defensive experts who can lock down areas and watch flanks, both on attacker and defender rounds.',
                'icon' => 'https://media.valorant-api.com/agents/1e58de9c-4950-5125-93e9-a0aee9f98746/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/5fc02f99-4091-4486-a531-98459a3e95e9/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/1e58de9c-4950-5125-93e9-a0aee9f98746/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/1e58de9c-4950-5125-93e9-a0aee9f98746/background.png',
                'color' => '#ffc300ff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 12,
                'ability_id' => 12,
                'name' => 'Harbor',
                'description' => 'Hailing from India’s coast, Harbor storms the field wielding ancient technology with dominion over water. He unleashes frothing rapids and crushing waves to shield his allies, or pummel those that oppose him.',
                'role' => 'Controller',
                'role_description' => 'Controllers are experts in slicing up dangerous territory to set their team up for success.',
                'icon' => 'https://media.valorant-api.com/agents/95b78ed7-4637-86d9-7e41-71ba8c293152/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/4ee40330-ecdd-4f2f-98a8-eb1243428373/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/95b78ed7-4637-86d9-7e41-71ba8c293152/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/95b78ed7-4637-86d9-7e41-71ba8c293152/background.png',
                'color' => '#f2d6a3ff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 13,
                'ability_id' => 13,
                'name' => 'Viper',
                'description' => 'The American Chemist, Viper deploys an array of poisonous chemical devices to control the battlefield and choke the enemy\'s vision. If the toxins don\'t kill her prey, her mindgames surely will.',
                'role' => 'Controller',
                'role_description' => 'Controllers are experts in slicing up dangerous territory to set their team up for success.',
                'icon' => 'https://media.valorant-api.com/agents/707eab51-4836-f488-046a-cda6bf494859/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/4ee40330-ecdd-4f2f-98a8-eb1243428373/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/707eab51-4836-f488-046a-cda6bf494859/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/707eab51-4836-f488-046a-cda6bf494859/background.png',
                'color' => '#89f476ff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 14,
                'ability_id' => 14,
                'name' => 'Phoenix',
                'description' => 'Hailing from the U.K., Phoenix\'s star power shines through in his fighting style, igniting the battlefield with flash and flare. Whether he\'s got backup or not, he\'s rushing in to fight on his own terms.',
                'role' => 'Duelist',
                'role_description' => 'Duelists are self-sufficient fraggers who their team expects, through abilities and skills, to get high frags and seek out engagements first.',
                'icon' => 'https://media.valorant-api.com/agents/eb93336a-449b-9c1b-0a54-a891f7921d69/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/dbe8757e-9e92-4ed4-b39f-9dfc589691d4/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/eb93336a-449b-9c1b-0a54-a891f7921d69/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/eb93336a-449b-9c1b-0a54-a891f7921d69/background.png',
                'color' => '#f7bf60ff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 15,
                'ability_id' => 15,
                'name' => 'Astra',
                'description' => 'Ghanaian Agent Astra harnesses the energies of the cosmos to reshape battlefields to her whim. With full command of her astral form and a talent for deep strategic foresight, she\'s always eons ahead of her enemy\'s next move.',
                'role' => 'Controller',
                'role_description' => 'Controllers are experts in slicing up dangerous territory to set their team up for success.',
                'icon' => 'https://media.valorant-api.com/agents/41fb69c1-4189-7b37-f117-bcaf1e96f1bf/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/4ee40330-ecdd-4f2f-98a8-eb1243428373/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/41fb69c1-4189-7b37-f117-bcaf1e96f1bf/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/41fb69c1-4189-7b37-f117-bcaf1e96f1bf/background.png',
                'color' => '#f47dc9ff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 16,
                'ability_id' => 16,
                'name' => 'Brimstone',
                'description' => 'Joining from the U.S.A., Brimstone\'s orbital arsenal ensures his squad always has the advantage. His ability to deliver utility precisely and safely make him the unmatched boots-on-the-ground commander.',
                'role' => 'Controller',
                'role_description' => 'Controllers are experts in slicing up dangerous territory to set their team up for success.',
                'icon' => 'https://media.valorant-api.com/agents/9f0d8ba9-4140-b941-57d3-a7ad57c6b417/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/4ee40330-ecdd-4f2f-98a8-eb1243428373/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/9f0d8ba9-4140-b941-57d3-a7ad57c6b417/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/9f0d8ba9-4140-b941-57d3-a7ad57c6b417/background.png',
                'color' => '#eb953fff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 17,
                'ability_id' => 17,
                'name' => 'Iso',
                'description' => 'Chinese fixer for hire Iso falls into a flow state to dismantle the opposition. Reconfiguring ambient energy into bulletproof protection, he advances with focus towards his next duel to the death.',
                'role' => 'Duelist',
                'role_description' => 'Duelists are self-sufficient fraggers who their team expects, through abilities and skills, to get high frags and seek out engagements first.',
                'icon' => 'https://media.valorant-api.com/agents/0e38b510-41a8-5780-5e8f-568b2a4f2d6c/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/dbe8757e-9e92-4ed4-b39f-9dfc589691d4/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/0e38b510-41a8-5780-5e8f-568b2a4f2d6c/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/0e38b510-41a8-5780-5e8f-568b2a4f2d6c/background.png',
                'color' => '#c4a1ffff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 18,
                'ability_id' => 18,
                'name' => 'Clove',
                'description' => 'Scottish troublemaker Clove makes mischief for enemies in both the heat of combat and the cold of death. The young immortal keeps foes guessing, even from beyond the grave, their return to the living only ever a moment away.',
                'role' => 'Controller',
                'role_description' => 'Controllers are experts in slicing up dangerous territory to set their team up for success.',
                'icon' => 'https://media.valorant-api.com/agents/1dbf2edd-4729-0984-3115-daa5eed44993/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/4ee40330-ecdd-4f2f-98a8-eb1243428373/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/1dbf2edd-4729-0984-3115-daa5eed44993/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/1dbf2edd-4729-0984-3115-daa5eed44993/background.png',
                'color' => '#f17cadff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 19,
                'ability_id' => 19,
                'name' => 'Neon',
                'description' => 'Filipino Agent Neon surges forward at shocking speeds, discharging bursts of bioelectric radiance as fast as her body generates it. She races ahead to catch enemies off guard then strikes them down quicker than lightning',
                'role' => 'Duelist',
                'role_description' => 'Duelists are self-sufficient fraggers who their team expects, through abilities and skills, to get high frags and seek out engagements first.',
                'icon' => 'https://media.valorant-api.com/agents/bb2a4828-46eb-8cd1-e765-15848195d751/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/dbe8757e-9e92-4ed4-b39f-9dfc589691d4/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/bb2a4828-46eb-8cd1-e765-15848195d751/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/bb2a4828-46eb-8cd1-e765-15848195d751/background.png',
                'color' => '#ba89ffff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 20,
                'ability_id' => 20,
                'name' => 'Yoru',
                'description' => 'Japanese native Yoru rips holes straight through reality to infiltrate enemy lines unseen. Using deception and aggression in equal measure, he gets the drop on each target before they know where to look.',
                'role' => 'Duelist',
                'role_description' => 'Duelists are self-sufficient fraggers who their team expects, through abilities and skills, to get high frags and seek out engagements first.',
                'icon' => 'https://media.valorant-api.com/agents/7f94d92c-4234-0a36-9646-3a87eb8b5c89/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/dbe8757e-9e92-4ed4-b39f-9dfc589691d4/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/7f94d92c-4234-0a36-9646-3a87eb8b5c89/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/7f94d92c-4234-0a36-9646-3a87eb8b5c89/background.png',
                'color' => '#66a8ffff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 21,
                'ability_id' => 21,
                'name' => 'Sage',
                'description' => 'The bastion of China, Sage creates safety for herself and her team wherever she goes. Able to revive fallen friends and stave off forceful assaults, she provides a calm center to a hellish battlefield.',
                'role' => 'Sentinel',
                'role_description' => 'Sentinels are defensive experts who can lock down areas and watch flanks, both on attacker and defender rounds.',
                'icon' => 'https://media.valorant-api.com/agents/569fdd95-4d10-43ab-ca70-79becc718b46/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/5fc02f99-4091-4486-a531-98459a3e95e9/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/569fdd95-4d10-43ab-ca70-79becc718b46/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/569fdd95-4d10-43ab-ca70-79becc718b46/background.png',
                'color' => '#7bfedeff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
            [
                'id' => 22,
                'ability_id' => 22,
                'name' => 'Reyna',
                'description' => 'Forged in the heart of Mexico, Reyna dominates single combat, popping off with each kill she scores. Her capability is only limited by her raw skill, making her sharply dependant on performance.',
                'role' => 'Duelist',
                'role_description' => 'Duelists are self-sufficient fraggers who their team expects, through abilities and skills, to get high frags and seek out engagements first.',
                'icon' => 'https://media.valorant-api.com/agents/a3bfb853-43b2-7238-a4f1-ad90e9e46bcc/displayiconsmall.png',
                'role_icon' => 'https://media.valorant-api.com/agents/roles/dbe8757e-9e92-4ed4-b39f-9dfc589691d4/displayicon.png',
                'portrait' => 'https://media.valorant-api.com/agents/a3bfb853-43b2-7238-a4f1-ad90e9e46bcc/fullportrait.png',
                'background' => 'https://media.valorant-api.com/agents/a3bfb853-43b2-7238-a4f1-ad90e9e46bcc/background.png',
                'color' => '#e46e77ff',
                'created_at' => NULL,
                'updated_at' => NULL
            ],
        ]);
    }
}
